apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-deployer
rules:
  - apiGroups: ["", "apps", "autoscaling", "networking.k8s.io"]
    resources:
      - namespaces
      - pods
      - pods/log
      - pods/exec
      - services
      - deployments
      - replicasets
      - statefulsets
      - configmaps
      - secrets
      - persistentvolumeclaims
      - horizontalpodautoscalers
      - ingresses
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-deployer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-deployer
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins
